<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.product-name{width:30%} .product-sku{width:30%}

</style>

<table>
  <tr>
    <th class="product-name">Product Name</th>
    <th class="product-sku">SKU</th>
  </tr>

<?php
	$productCollection = $block->getProductCollection();
	foreach ($productCollection as $product) {	    
	    echo '<tr>             
	              <td>'.$product->getName().'</td>
	              <td>'.$product->getSku().'</td>
	          </tr>';
	}

?>
</table>

</body>
</html>